~FT[15/08/97, 14:29:14]: ~RS~OLNeil:~RS test
~FT[15/08/97, 14:29:16]: ~RS~OLNeil:~RS test123
~FT[23/08/97, 12:25:44]: ~RS~OLNeil:~RS hello
~FT[25/08/97, 11:36:38]: ~RS~OLNeil:~RS test
~FT[25/08/97, 12:37:50]: ~RS~OLNeil:~RS this is a long test message , i hope it works
~FT[28/10/97, 10:54:39]: ~RS~OLNeil:~RS test
~FT[10/01/98, 13:07:54]: ~RS~OLNeil:~RS test
~FT[10/01/98, 13:08:41]: ~RS~OLNeil:~RS test again
